# Generated by Django 5.1.1 on 2025-01-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinventory',
            name='cars_value',
            field=models.FloatField(null=True),
        ),
    ]
